version: "3.8"

services:
  localstack:
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=default
      - AWS_SECRET_ACCESS_KEY=secret
  application:
    build: .
    ports: 
      - "5000:5000"
    environment: 
      - S3_BUCKET=measurements-bucket
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=default
      - AWS_SECRET_ACCESS_KEY=secret